# Generated by Django 3.1.5 on 2021-01-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNumber', models.CharField(max_length=1000)),
                ('cardName', models.CharField(max_length=1000)),
                ('secNumber', models.CharField(max_length=1000)),
                ('expiry', models.DateField(blank=True)),
                ('amount', models.CharField(max_length=1000)),
            ],
        ),
    ]
